### ISSUE TITLE
Unable to install the gem in any Rails app

### ISSUE THREAD

**Issue by swaathi** [meilisearch/meilisearch-rails#107]
**Description**
I added `gem 'meilisearch-rails'` to by Gemfile and did a bundle install. I then go to rails console and just type in,

```
irb(main):007:0> MeiliSearch::Rails
Traceback (most recent call last):
        2: from (irb):6
        1: from (irb):7:in `rescue in irb_binding'
NameError (uninitialized constant MeiliSearch::Rails)
irb(main):008:0>
```

I tried this on,

1. Rails 5.2.3 / Ruby 2.6.3
2. Rails 7.1.0.alpha / Ruby 2.7.3 (This is a completely new Rails app with no dependencies other than core Rails.)

Tried it even on basic IRB shell. Same error.

**Expected behavior**
The gem should load!

**Current behavior**
Doesn't load. When I do,

```
irb(main):001:0> require 'meilisearch-rails'
=> false
```

So it has been required but it can not find the module `MeiliSearch::Rails`. 

We (@heertheeswaran and I) downgraded to 0.3 as well, same bug. Please fix ASAP. We want to move from Algolia to Meili.

**Environment (please complete the following information):**
- OS: macOS Monterey, 12.2 Beta
- Meilisearch version: meilisearch (0.18.0)
- meilisearch-rails version: meilisearch-rails (0.4.1)

**Comment by brunoocasali** [comment]
Hello @swaathi, first of all, I'm so sorry about this, this shouldn’t have happened. 

The real problem is because you are reading **the new in-repository** documentation, we are about to release a new version which contains a `breaking-change` and unfortunately, it took me more time than expected 😅.

Anyway, to overcome this problem you can follow this documentation: https://github.com/meilisearch/meilisearch-rails/tree/v0.4.1 that correctly belongs to the version you are using.

Btw: That's why even you and @heertheeswaran downgrading didn’t solve the problem if you intend to use the old version you should be aware of the compatibility with the Meilisearch server which only supports `v0.24`.

I should release a new meilisearch-rails version `v0.5.0` in a few days to match the implementation and the documentation in the `main` branch.

Feel free to reach out with any other problems/questions you have! 😊

**Comment by heertheeswaran** [comment]
@brunoocasali Yeah figured it out. Thanks for the support.

**Comment by brunoocasali** [comment]
@swaathi and @heertheeswaran I'm finishing the release notes of the new version v0.5.0 and the main and the latest release should be compatible now. So I'm closing this issue, any other problems feel free to open an issue!

Thanks for using Meilisearch! ❤️
