### ISSUE TITLE
Add ability to specify meilisearch_host / api_key per model

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch-rails#190]
It would be great if we could use a different meilisearch_host / api_key in different models, rather than defining this in an initializer for all models. Is this currently possible?

**Comment by brunoocasali** [comment]
Hi @jeremylynch!

Unfortunately, this is not possible I would like to understand better your intentions with this kind of configuration. Can you give some more context here? Thanks!

**Comment by jeremylynch** [comment]
We are running into performance issues with very long tasks lists. Ideally, we would distribute meilisearch across multiple instances with a shared index, but this is not possible. An alternative for us, is to use different servers for different models so we can share the load that way - but it sounds like this isn't possible?

**Comment by gmourier** [comment]
Hi @jeremylynch!

> We are running into performance issues with very long task lists.

If I understand correctly, you would like to get around the indexing speed problems by having several servers, one per index (model), so as not to share the task queue for all your models (_the task queue is shared for all indexes_)? Let me know if I'm wrong!

If this is the case, we have some tips to share with you that you could try to see if it solves this problem.

- Enable auto-batching on Meilisearch startup, e.g `--enable-auto-batching`. Meilisearch will group the additions and updates of documents if there are several for the same indexes within the task queue. I think in your case it can help a lot since data structures computations will be mutualized for all tasks in a batch.
- I think it's already done, but if in doubt, here's another tip. If you can define the `searchablesAttributes`, `filterableAttributes`, `sortableAttributes` before you start sending documents in each model, it helps!

I have more questions I would like to ask you;

- How many models do you have and how many documents does this represent?
- Do you encounter any blockage during the first indexing? Or is it a slowdown as your app grows with users?

> An alternative for us, is to use different servers for different models so we can share the load that way

I think it's possible with some sort of a workaround. 

Since `v0.28`, when you create an API Key, you can give it an `uid`;  If you create API Keys with the same `uid` and the same master key in each Meilisearch instance, the resulting API Key `key` field should be the same and you can use that one in the rails client;

This way, you could use that API Key and be able to reach every different Meilisearch instance. 

But before trying this solution, I encourage you to test the indexing tips to see if it solves your problem!

Thanks!

**Comment by brunoocasali** [comment]
Hi @jeremylynch, do you still have the issue after the @gmourier comment?

**Comment by jeremylynch** [comment]
Hi @brunoocasali, we are handling large volumes of documents, and to help reduce the load on a single server, we would prefer to distribute this across multiple meileisearch instances - are you able to give an example of how we could implement a different meileisearch host/api_key per model?

**Comment by brunoocasali** [comment]
Hi @jeremylynch!

Currently, Meilisearch does not support that possibility. You can check this and other feature requests [here in our roadmap](https://roadmap.meilisearch.com/c/24-high-availibility).
The high availability is in our plans, but I can’t give you a due date. 

But I encourage you to send some details about your workload [here](https://roadmap.meilisearch.com/c/24-high-availibility) if you don't want to share them publically here.

CC: @gmourier

**Comment by brunoocasali** [comment]
I will close this issue since the HA is now a priority, so this will probably be fixed then.
