### ISSUE TITLE
Try to create the index when a new document is indexed.

### ISSUE THREAD

**Issue by smarquezs** [meilisearch/meilisearch-rails#198]
Playing with the `/tasks` API I found some failed ones.

```json
		{
			"uid": 1083,
			"indexUid": "CouponRequest_development",
			"status": "failed",
			"type": "indexCreation",
			"details": {
				"primaryKey": "id"
			},
			"error": {
				"message": "Index `CouponRequest_development` already exists.",
				"code": "index_already_exists",
				"type": "invalid_request",
				"link": "https://docs.meilisearch.com/errors#index_already_exists"
			},
			"duration": "PT0.002145S",
			"enqueuedAt": "2022-10-07T19:57:29.806189Z",
			"startedAt": "2022-10-07T19:57:29.811471Z",
			"finishedAt": "2022-10-07T19:57:29.813616Z"
		}
```

Digging in the code base I found every time the `ms_reindex!` is called, this method is calling another method called `ms_ensure_init`, as you can see [here](https://github.com/meilisearch/meilisearch-rails/blob/d40c97ef2ef740f30529fa4817a509119c5643d2/lib/meilisearch-rails.rb#L507), basically every time a new document is indexed it tries to create the index.

So, my questions are, is there any option to disable this behavior? do we have any impact in the server creating an extra task in every reindex call?

**Comment by brunoocasali** [comment]
Hi @smarquezs thanks for opening this issue!

The current implementation tries to create a new index only if the memoized value are not saved in memory yet. So if you reuse the same client, you'll not have such behavior.

After v0.29 we introduced a way to flush old tasks so, it will not be a problem in terms of disk neither performance.

I'm not aware about how is your production environment but if you have to initialize a meilisearch instance everytime you have to add a new document may you will suffer with some kind of network overhead.

I think we could introduce a feature to overcome this situation. Feel free to send a PR for that ;)

Thanks again!

**Comment by brunoocasali** [comment]
I don't see why this is an issue, and why I kept it open in the past. So I'm going to close it. Let me know if I'm wrong!

**Comment by mech** [comment]
From the perspective of the meilisearch-rails gem, how do we get that memoized version of the client?

I see whenever we call `MeiliSearch::Rails.client`, it will always give us back a new instance with different object_id.

I ask this because whenever I save a model through the Web UI, there always seems to have an `indexCreation` as well as `settingsUpdate` happening together.

And I noticed that the processes can take some time to finish even if my local development only is updating a single model only.

**Comment by brunoocasali** [comment]
Hi @mech! 

> I see whenever we call `MeiliSearch::Rails.client`, it will always give us back a new instance with different object_id.

Yes, indeed, so far, the whole gem is tough to maintain because I can trust that much in the test suite, and by the time I tried to make the client a memoized one, I had trouble making it work due to a leak in the specs, and the refactor would be too time-consuming for me right now.

So, I recommend instantiating a new `MeiliSearch::Rails.client` and keeping it somewhere in your code (maybe an initializer?) if you call the client directly.

About the settings and index creation task I'll answer in the other thread #280
