### ISSUE TITLE
Is there a way to get facet_distribution together with eager loading?

### ISSUE THREAD

**Issue by mech** [meilisearch/meilisearch-rails#235]
Is there a way to get back facets with eager loading like the following?

```ruby
result = Candidate.includes(:some_assoc).search("", facets: ["nationality"])

result.hits  #=> An array of ActiveRecord objects
result.facets #=> Facet distribution
result.processing_time #=> How long it takes
```

**Comment by brunoocasali** [comment]
Hi @mech 

When you use `#search`, you have some extended methods in that array, the array returned contains a list of `ActiveRecord` objects but it also contains some extras like: `#raw_answer` and `#facets_distribution`.

It means you can call: 

```rb
result = Candidate.includes(:some_assoc).search("", facets: ["nationality"])

result  #=> An array of ActiveRecord objects
result.facets_distribution #=> Facet distribution
result.raw_answer['processingTimeMs'] #=> How long it takes
```

You can also use `raw_search` directly if you want. If you have more issues, don't hesitate! And sorry because your issue flew away off my radar :/

**Comment by mech** [comment]
Wow, tks so much, not sure how come I missed those thing. Appreciated 👏
