### ISSUE TITLE
Add meilisearch backend version check

### ISSUE THREAD

**Issue by jitingcn** [meilisearch/meilisearch-rails#95]
**Description**
When I encountered a problem with meilisearch not being able to create model index after upgrading gems yesterday, after an hour of troubleshooting I found that this was caused by an incompatible version of meilisearch. I thought it would be a good idea to add a version check in the rails initializer.

**Basic example**
Some other libraries I have used have similar functionality, for example https://github.com/stimulusreflex/stimulus_reflex/blob/master/lib/stimulus_reflex/utils/sanity_checker.rb

**Comment by brunoocasali** [comment]
Hey @jitingcn, thanks for raising this concern with us!

I really think that could be an awesome addition to the integration not only in the rails one but all the others!

@curquiza let me know if I'm wrong, but we do not have this kind of check inside our integrations right?

This is especially useful in this particular moment because the engine v1 was not released yet and most of the time our integrations are not backgrounded compatible with older versions.

Doing this particular check could help our users to prevent problems in projects that are using a CI + [optimistic version control](https://guides.rubygems.org/patterns/#pessimistic-version-constraint).

**Comment by jitingcn** [comment]
I think we could encode a compatible version range in the library file and then try to connect to the /version endpoint of meilisearch to check version compatibility when rails is initialised.

**Comment by brunoocasali** [comment]
I agree this will be an excellent addition to the meilisearch SDKs (not only to rails), but since this would require a lot of work and Meilisearch is stable now, we don't think that should be harmful as it was in the v0.* era :)

Im closing this, thanks a lot for using Meilisearch @jitingcn ❤️
